/**
 * Legal Safety Policy & Content Generation Rules
 * 
 * Ensures AI-generated legal content maintains professional standards,
 * includes necessary disclaimers, and follows legal best practices.
 */

export const LEGAL_DISCLAIMERS = {
    general: `IMPORTANT LEGAL DISCLAIMER:
This document has been generated by an AI system and is provided for informational purposes only. 
This is NOT a substitute for professional legal advice from a qualified attorney. 
Laws vary significantly by jurisdiction, and your specific circumstances may require customized legal counsel.
Always consult with a licensed attorney in your jurisdiction before relying on this document.`,

    contract: `CONTRACT DISCLAIMER:
This contract template has been AI-generated based on general contract law principles.
It may not comply with specific local, state, or international laws.
Before execution, have it reviewed by a qualified attorney licensed in your jurisdiction.
Both parties should understand all terms and obligations before signing.`,

    nda: `NDA DISCLAIMER:
This Non-Disclosure Agreement template has been AI-generated.
NDAs must be carefully tailored to your specific business needs and comply with local laws.
Consult a qualified attorney to ensure this agreement protects your interests adequately.`,

    employment: `EMPLOYMENT CONTRACT DISCLAIMER:
This employment contract template is AI-generated and may not comply with employment laws in your jurisdiction.
Employment laws vary significantly by location and may include mandatory provisions not covered here.
Consult an employment attorney before offering this contract to employees.`,

    loan: `LOAN AGREEMENT DISCLAIMER:
This loan agreement template is AI-generated for informational purposes.
Lending is heavily regulated and compliance with consumer protection laws is critical.
Consult a qualified attorney and financial advisor before using for actual lending.`,

    lease: `LEASE AGREEMENT DISCLAIMER:
This lease agreement template is AI-generated but may not comply with local landlord-tenant laws.
Many jurisdictions have mandatory lease provisions and specific disclosure requirements.
Have a local attorney review this before using it as an actual lease agreement.`,
};

export const LEGAL_SAFEGUARDS = {
    // Content restrictions
    restrictedTopics: [
        'illegal activities',
        'criminal defense',
        'tax evasion',
        'fraud',
        'money laundering',
        'terrorism',
        'violence',
        'harassment',
    ],

    // Safety checks for document generation
    safetyChecks: [
        'content_moderation',
        'legal_accuracy_verification',
        'jurisdiction_compliance',
        'disclosure_inclusion',
        'professional_language',
    ],

    // Mandatory elements for different document types
    mandatoryElements: {
        contract: [
            'parties_identification',
            'effective_date',
            'consideration',
            'terms_and_conditions',
            'termination_clause',
            'dispute_resolution',
            'governing_law',
            'legal_disclaimer',
        ],
        nda: [
            'parties_identification',
            'definition_of_confidential_info',
            'obligations_of_receiving_party',
            'exclusions_from_confidentiality',
            'duration_of_confidentiality',
            'return_of_information',
            'legal_disclaimer',
        ],
        employment: [
            'employee_name_and_title',
            'employment_type_status',
            'compensation_details',
            'job_duties_and_responsibilities',
            'work_hours_and_location',
            'at_will_employment_statement',
            'confidentiality_clause',
            'non_compete_if_applicable',
            'dispute_resolution',
            'governing_law',
            'legal_disclaimer',
        ],
        loan: [
            'borrower_and_lender_identification',
            'principal_amount',
            'interest_rate',
            'repayment_schedule',
            'default_provisions',
            'prepayment_terms',
            'security_or_collateral_if_applicable',
            'default_interest_rate',
            'legal_disclaimer',
        ],
        lease: [
            'landlord_and_tenant_identification',
            'property_description',
            'lease_term',
            'rent_amount_and_payment_terms',
            'security_deposit',
            'maintenance_and_repairs',
            'lease_renewal_terms',
            'default_and_termination',
            'legal_disclaimer',
        ],
    },

    // Required language for documents
    requiredLanguage: {
        governingLaw: 'This agreement shall be governed by and construed in accordance with the laws of [INSERT JURISDICTION], without regard to its conflict of law principles.',
        severability: 'If any provision of this agreement is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.',
        entireAgreement: 'This agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, and agreements.',
        amendments: 'No amendment or modification of this agreement shall be effective unless in writing and signed by both parties.',
    },
};

export const PROMPT_TEMPLATES = {
    // Enhanced prompts for legal document generation
    contract: `You are a professional legal document generator. Create a professional agreement between the specified parties.

IMPORTANT SAFETY INSTRUCTIONS:
1. Only generate legitimate business contracts
2. Use clear, professional legal language
3. Include all mandatory legal elements: parties, terms, effective date, signatures
4. Add a "Governing Law" section
5. Include a "Severability" clause
6. Add an "Entire Agreement" statement
7. Do NOT include provisions for illegal activities
8. Include standard dispute resolution language
9. Make the document clear and understandable
10. Ensure all dates and financial terms are reasonable and clear

REQUIRED ELEMENTS TO INCLUDE:
${LEGAL_SAFEGUARDS.mandatoryElements.contract.join('\n')}

DISCLAIMER: Include a clear disclaimer stating this is a template and requires legal review.

User Request Details: {userDetails}

Generate a professional, legally sound contract template:`,

    nda: `You are a professional legal document generator. Create a Non-Disclosure Agreement (NDA).

IMPORTANT SAFETY INSTRUCTIONS:
1. Generate only legitimate NDAs for business purposes
2. Define what is and is not considered confidential information
3. Specify the obligations of the receiving party
4. Include confidentiality duration
5. Add standard exclusions from confidentiality (public domain, independently developed, etc.)
6. Include return/destruction of information clause
7. Use clear, professional language
8. Do NOT include illegal restrictions or unconscionable terms
9. Include governing law provision
10. Add standard dispute resolution language

REQUIRED ELEMENTS TO INCLUDE:
${LEGAL_SAFEGUARDS.mandatoryElements.nda.join('\n')}

DISCLAIMER: Include a clear disclaimer stating this is a template and requires legal review.

User Request Details: {userDetails}

Generate a professional NDA template:`,

    employment: `You are a professional legal document generator. Create an Employment Contract.

IMPORTANT SAFETY INSTRUCTIONS:
1. Generate only legitimate employment contracts
2. Clearly state employment type (full-time, part-time, contract)
3. Include complete compensation details
4. Specify job duties and responsibilities
5. State working hours and location
6. Include proper at-will employment language (or alternative as specified)
7. Add confidentiality and IP assignment clauses if applicable
8. Include dispute resolution procedures
9. Comply with employment law standards
10. Do NOT include illegal provisions, wage theft, or discriminatory terms

REQUIRED ELEMENTS TO INCLUDE:
${LEGAL_SAFEGUARDS.mandatoryElements.employment.join('\n')}

DISCLAIMER: Include a disclaimer that employment contracts must comply with local employment laws.

User Request Details: {userDetails}

Generate a professional employment contract template:`,

    loan: `You are a professional legal document generator. Create a Loan Agreement.

IMPORTANT SAFETY INSTRUCTIONS:
1. Generate only for legitimate lending purposes
2. Clearly specify the principal amount
3. Include actual, compliant interest rate (must comply with usury laws)
4. Provide clear repayment schedule
5. Include default provisions with reasonable penalties
6. Add prepayment terms
7. Specify any collateral or security
8. Include default interest rate (if applicable)
9. Use clear financial terms
10. Do NOT include predatory lending terms or illegal provisions

REQUIRED ELEMENTS TO INCLUDE:
${LEGAL_SAFEGUARDS.mandatoryElements.loan.join('\n')}

DISCLAIMER: Include disclaimer about lending law compliance requirements.

User Request Details: {userDetails}

Generate a professional loan agreement template:`,

    lease: `You are a professional legal document generator. Create a Lease Agreement.

IMPORTANT SAFETY INSTRUCTIONS:
1. Generate only for legitimate rental purposes
2. Clearly identify landlord and tenant
3. Provide detailed property description
4. Specify lease term (start and end date)
5. State rent amount and payment terms clearly
6. Specify security deposit amount
7. Clarify maintenance and repair responsibilities
8. Include lease renewal terms
9. Add default and termination provisions
10. Comply with landlord-tenant law standards

REQUIRED ELEMENTS TO INCLUDE:
${LEGAL_SAFEGUARDS.mandatoryElements.lease.join('\n')}

DISCLAIMER: Include disclaimer about local landlord-tenant law compliance.

User Request Details: {userDetails}

Generate a professional lease agreement template:`,
};

/**
 * Validates document content against legal safety guidelines
 */
export function validateLegalContent(
    content: string,
    documentType: string
): { isValid: boolean; violations: string[] } {
    const violations: string[] = [];

    // Check for restricted topics
    const lowerContent = content.toLowerCase();
    for (const topic of LEGAL_SAFEGUARDS.restrictedTopics) {
        if (lowerContent.includes(topic)) {
            violations.push(`Content mentions restricted topic: "${topic}"`);
        }
    }

    // Check for mandatory elements
    const mandatoryForType = LEGAL_SAFEGUARDS.mandatoryElements[
        documentType as keyof typeof LEGAL_SAFEGUARDS.mandatoryElements
    ];

    if (mandatoryForType) {
        for (const element of mandatoryForType) {
            const elementCheck = element.replace(/_/g, ' ');
            if (!lowerContent.includes(elementCheck)) {
                // Only warn, don't fail validation
                violations.push(`Warning: Missing recommended element: "${elementCheck}"`);
            }
        }
    }

    // Check for required language patterns
    let hasGoverningSectionOrLaw = false;

    if (
        lowerContent.includes('governing law') ||
        lowerContent.includes('jurisdiction')
    ) {
        hasGoverningSectionOrLaw = true;
    }

    if (
        lowerContent.includes('disclaimer') ||
        lowerContent.includes('important') ||
        lowerContent.includes('legal advice')
    ) {
        // Has disclaimer/warning - good
    }

    if (!hasGoverningSectionOrLaw) {
        violations.push('Warning: No governing law or jurisdiction clause found');
    }

    return {
        isValid: violations.every((v) => v.startsWith('Warning:')),
        violations,
    };
}

/**
 * Gets the appropriate disclaimer for a document type
 */
export function getDisclaimer(documentType: string): string {
    return (
        LEGAL_DISCLAIMERS[
        documentType as keyof typeof LEGAL_DISCLAIMERS
        ] || LEGAL_DISCLAIMERS.general
    );
}

/**
 * Formats legal content with proper structure and disclaimer
 */
export function formatLegalDocument(
    content: string,
    documentType: string,
    generatedDate: Date = new Date()
): string {
    const disclaimer = getDisclaimer(documentType);

    return `# ${documentType.toUpperCase()}

*Generated on ${generatedDate.toLocaleDateString()} ${generatedDate.toLocaleTimeString()} by LawCraft AI*

${disclaimer}

---

${content}

---

**LEGAL NOTICE**: This document was generated by AI and requires professional legal review. Consult a qualified attorney before executing or relying on this document. Laws vary by jurisdiction. No attorney-client relationship is created by using this service.
`;
}

export default {
    LEGAL_DISCLAIMERS,
    LEGAL_SAFEGUARDS,
    PROMPT_TEMPLATES,
    validateLegalContent,
    getDisclaimer,
    formatLegalDocument,
};
